version: 2
jobs:
  build-docker-image:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t gifnksm/gifcc-build:archlinux -f misc/Dockerfile.archlinux misc
      - run: docker push gifnksm/gifcc-build:archlinux

  stage1-build:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - run: make stage1
      - save_cache:
          key: stage1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - target/stage1
            - src/include_path.h
  stage2-build:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - restore_cache:
          key: stage1-{{ .Environment.CIRCLE_SHA1 }}
      - run: touch target/stage*/*
      - run: make stage2
      - save_cache:
          key: stage2-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - target/stage1
            - target/stage2
            - src/include_path.h
  stage3-build:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - restore_cache:
          key: stage2-{{ .Environment.CIRCLE_SHA1 }}
      - run: touch target/stage*/*
      - run: make stage3
      - save_cache:
          key: stage3-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - target/stage1
            - target/stage2
            - target/stage3
            - src/include_path.h

  stage1-test:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - restore_cache:
          key: stage1-{{ .Environment.CIRCLE_SHA1 }}
      - run: touch target/stage*/*
      - run: make stage1-test-full
      - run:
          command: |
            mkdir -p target/test-results/stage1-c-testsuite
            tap-xunit < target/stage1/c-testsuite/result.tap > target/test-results/stage1-c-testsuite/results.xml || true
      - store_test_results:
          path: target/test-results
  stage2-test:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - restore_cache:
          key: stage2-{{ .Environment.CIRCLE_SHA1 }}
      - run: touch target/stage*/*
      - run: make stage2-test-full
      - run:
          command: |
            mkdir -p target/test-results/stage2-c-testsuite
            tap-xunit < target/stage2/c-testsuite/result.tap > target/test-results/stage2-c-testsuite/results.xml || true
      - store_test_results:
          path: target/test-results
  stage3-test:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - restore_cache:
          key: stage3-{{ .Environment.CIRCLE_SHA1 }}
      - run: touch target/stage*/*
      - run: make stage3-test-full
      - run:
          command: |
            mkdir -p target/test-results/stage3-c-testsuite
            tap-xunit < target/stage3/c-testsuite/result.tap > target/test-results/stage3-c-testsuite/results.xml || true
      - store_test_results:
          path: target/test-results

workflows:
  version: 2
  commit:
    jobs:
      - stage1-build
      - stage2-build:
          requires:
            - stage1-build
      - stage3-build:
          requires:
            - stage2-build
      - stage1-test:
          requires:
            - stage1-build
      - stage2-test:
          requires:
            - stage2-build
      - stage3-test:
          requires:
            - stage3-build

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docker-image
