version: 2
jobs:
  build-docker-image:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t gifnksm/gifcc-build:archlinux -f misc/Dockerfile.archlinux misc
      - run: docker push gifnksm/gifcc-build:archlinux

  build:
    docker:
      - image: gifnksm/gifcc-build:archlinux
    steps:
      - checkout
      - run: make
      - run: make test-full
      - run:
          command: |
            mkdir -p target/test-results/stage1-c-testsuite
            tap-xunit < target/stage1/c-testsuite > target/test-results/stage1-c-testsuite/results.xml || true
      - store_test_results:
          path: target/test-results

workflows:
  version: 2
  commit:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docker-image
