#!/bin/bash

set -e
set -u

if ! test "x86_64" = "$(uname -m)"; then
    echo "incorrect host for test" 1>&2
    exit 1
fi

input=$1
test=$(basename ${input})

cat ${input}

set -x

if ! gifcc "${input}" --emit all --asm-syntax att -o "${OUTDIR}/${test}.s"; then
    exit 1
fi

if ! gcc -lm -o "${OUTDIR}/${test}.bin" "${OUTDIR}/${test}.s"; then
    exit 1
fi

if ! "${OUTDIR}/${test}.bin" > "${OUTDIR}/${test}.output" 2>&1; then
    exit 1
fi

if ! diff -u "${input}.expected" "${OUTDIR}/${test}.output"; then
    exit 1
fi
